export const ADD_CART = "ADD_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
